options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: ALLOW_LOOSE

steps:
  - name: "gcr.io/cloud-builders/git"
    entrypoint: /bin/bash
    args:
      - -c
      - |
        git fetch --depth=50 origin main
        CHANGED_APPS=$(git diff --name-only origin/main...HEAD | grep '^apps/' | cut -d/ -f2 | sort -u)
        echo "Changed apps: $$CHANGED_APPS"

substitutions:
  _AR_HOSTNAME: "asia-docker.pkg.dev" # ex) asia-docker.pkg.dev
  _AR_PROJECT_ID: "my-gcp-project"
  _AR_REPOSITORY: "my-repo"
  _CLOUD_RUN_REGION: "asia-northeast3"
timeout: "1800s"
