# cloudbuild.yaml
steps:
  # 1. Node 환경 설정 및 Turborepo 설치
  - name: "node:20-alpine"
    id: "Setup Node & PNPM"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        npm install -g pnpm
        pnpm install --frozen-lockfile

  # 2. 변경된 landing 앱만 빌드 & export
  - name: "node:20-alpine"
    id: "Build Changed Landing Apps"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Checking changed landing apps..."
        CHANGED_APPS=$(git diff --name-only origin/main...HEAD | grep '^apps/landing-' | cut -d/ -f2 | sort -u)

        if [ -z "$CHANGED_APPS" ]; then
          echo "No landing apps changed. Skipping build."
          exit 0
        fi

        echo "Changed apps: $CHANGED_APPS"

        for APP in $CHANGED_APPS; do
          echo "Building $APP..."
          pnpm install --filter=$APP...
          pnpm --filter=$APP run build
          pnpm --filter=$APP next export

          echo "Uploading $APP to GCS..."
          gsutil -m rsync -r apps/$APP/out gs://${_GCS_BUCKET}/$APP/

          echo "Invalidate CDN cache for $APP..."
          gcloud compute url-maps invalidate-cdn-cache ${_CDN_URLMAP} \
            --path "/$APP/*"
        done
options:
  logging: CLOUD_LOGGING_ONLY

# 매개변수
substitutions:
  _GCS_BUCKET: "landing-jys"
  _CDN_URLMAP: "landing-jys"

timeout: 1800s
