steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:latest"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        npm install -g pnpm
        pnpm install --filter=apps/${_REPO_NAME}...
        pnpm --filter=apps/${_REPO_NAME} run build
        pnpm --filter=apps/${_REPO_NAME} next export
        gsutil -m rsync -r apps/${_REPO_NAME}/out gs://${_GCS_BUCKET}/${_REPO_NAME}/
        gcloud compute url-maps invalidate-cdn-cache ${_CDN_URLMAP} --path "/${_REPO_NAME}/*"

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _GCS_BUCKET: "landing-jys"
  _CDN_URLMAP: "landing-jys"
  _REPO_NAME: "" # 트리거에서 이 변수로 앱 이름 넘겨줌
timeout: 1800s
