# cloudbuild.yaml
steps:
  - name: "node:20-alpine"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        apk add --no-cache git

        # 수정된 landing 앱 감지
        CHANGED_APPS=$(git fetch origin main && git diff --name-only origin/main...HEAD | grep '^apps/landing-' | cut -d/ -f2 | sort -u)

        if [ -z "$CHANGED_APPS" ]; then
          echo "No landing apps changed. Skipping build."
          exit 0
        fi

        echo "Changed apps: $CHANGED_APPS"

        for APP in $CHANGED_APPS; do
          echo "Building $APP..."
          pnpm install --filter=$APP...
          pnpm --filter=$APP run build
          pnpm --filter=$APP next export
          gsutil -m rsync -r apps/$APP/out gs://${_GCS_BUCKET}/$APP/
          gcloud compute url-maps invalidate-cdn-cache ${_CDN_URLMAP} --path "/$APP/*"
        done
options:
  logging: CLOUD_LOGGING_ONLY

# 매개변수
substitutions:
  _GCS_BUCKET: "landing-jys"
  _CDN_URLMAP: "landing-jys"

timeout: 1800s
