steps:
  - name: "node:20-alpine"
    id: "Setup Node & PNPM"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        npm install -g pnpm
        pnpm install --frozen-lockfile

  - name: "node:20-alpine"
    id: "Build Landing App"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        if [ -z "${_REPO_NAME}" ]; then
          echo "No landing app specified. Skipping build."
          exit 0
        fi

        echo "Building ${_REPO_NAME}..."
        pnpm install --filter=${_REPO_NAME}...
        pnpm --filter=${_REPO_NAME} run build
        pnpm --filter=${_REPO_NAME} next export
        gsutil -m rsync -r apps/${_REPO_NAME}/out gs://${_GCS_BUCKET}/${_REPO_NAME}/
        gcloud compute url-maps invalidate-cdn-cache ${_CDN_URLMAP} --path "/${_REPO_NAME}/*"

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _GCS_BUCKET: "landing-jys"
  _CDN_URLMAP: "landing-jys"
  _REPO_NAME: "" # 트리거에서 이 변수로 앱 이름 넘겨줌
timeout: 1800s
