steps:
  - name: "node:20-alpine"
    id: "Setup Node & PNPM"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        npm install -g pnpm
        pnpm install --frozen-lockfile

  - name: "node:20-alpine"
    id: "Build Changed Landing Apps"
    entrypoint: "bash"
    args:
      - "./build-changed.sh"

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _GCS_BUCKET: "landing-jys"
  _CDN_URLMAP: "landing-jys"

timeout: 1800s
