options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: ALLOW_LOOSE

steps:
  - name: "gcr.io/cloud-builders/git"
    entrypoint: /bin/bash
    args:
      - -c
      - |
        git fetch --depth=2 origin main
        echo hello
        git  log
        git --no-pager diff --name-only HEAD^ HEAD | grep "/" | cut -d/ -f1 | sort | uniq > /workspace/diff.txt
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: /bin/bash
    args:
      - -c
      - |
        while read line
        do 
        config="${line}/cloudbuild.yaml"
        echo $config
        if [[ ! -f "${config}" ]]; then
         echo "no such file"
         continue
        fi
        gcloud builds submit $line --config=${config}
        done < /workspace/diff.txt

substitutions:
  _AR_HOSTNAME: "asia-docker.pkg.dev" # ex) asia-docker.pkg.dev
  _AR_PROJECT_ID: "my-gcp-project"
  _AR_REPOSITORY: "my-repo"
  _CLOUD_RUN_REGION: "asia-northeast3"
timeout: "1800s"
